### ISSUE TITLE
Course aggregate view takes first when it should filter

### ISSUE THREAD

**Issue by bri25yu** [compserv/hkn-rails#304]
The course aggregate view https://github.com/compserv/hkn-rails/blob/master/config/routes.rb#L246 looks for effectiveness or worthwhileness questions https://github.com/compserv/hkn-rails/blob/master/app/controllers/coursesurveys_controller.rb#L119 and takes only the first one by the corresponding keyword https://github.com/compserv/hkn-rails/blob/master/app/models/survey_question.rb#L34 where it should be filtering instead e.g. https://github.com/compserv/hkn-rails/blob/master/app/controllers/coursesurveys_controller.rb#L139.

**Comment by bri25yu** [comment]
There are probably more instance of this i.e. plenty of results when searching by `find_by_keyword` and they should all probably filtering rather than taking just the first one.

**Comment by lo-maxwell** [comment]
Resolved (rather inefficiently, if anyone feels like optimizing it)
